version: '3'

services:
  solana-validator:
    image: solanalabs/solana:stable
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    volumes:
      - ./ledger:/root/ledger
    command: solana-test-validator --rpc-port 8899 --ledger /root/ledger
    environment:
      - RUST_LOG=solana=info

  anchor-build:
    image: solanalabs/solana:stable
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        apt-get update && apt-get install -y git && 
        curl -sL https://deb.nodesource.com/setup_18.x | bash - && 
        apt-get install -y nodejs && 
        npm install -g @coral-xyz/anchor-cli && 
        anchor build
      "
    depends_on:
      - solana-validator

  anchor-client:
    image: solanalabs/solana:stable
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        apt-get update && apt-get install -y git && 
        curl -sL https://deb.nodesource.com/setup_18.x | bash - && 
        apt-get install -y nodejs && 
        npm install -g @coral-xyz/anchor-cli && 
        tail -f /dev/null
      "
    environment:
      - ANCHOR_PROVIDER_URL=http://solana-validator:8899
      - ANCHOR_WALLET=/app/.anchor/wallet/wallet.json

networks:
  default:
    driver: bridge