version: '3'

services:
  solana-validator:
    image: solanalabs/solana:stable
    container_name: solana-validator
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    volumes:
      - ./target/deploy:/app/deploy
      - ./test-ledger:/test-ledger
    command: >
      bash -c "
        apt-get update && apt-get install -y curl netcat &&
        echo 'Starting validator...' &&
        solana-test-validator 
          --ledger /test-ledger
          --bind-address 0.0.0.0
          --rpc-port 8899
          --rpc-bind-address 0.0.0.0
          --reset
          --slots-per-epoch 32
          --tick-per-slot 8
          --no-bpf-jit"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8899", "-X", "POST", "-H", "Content-Type: application/json", "-d", "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getHealth\"}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  program-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: program-builder
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    command: >
      bash -c "
        apt-get update && apt-get install -y curl &&
        echo 'Waiting for Solana validator...' &&
        while ! curl -sf http://solana-validator:8899 -X POST -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getHealth\"}'; do
          echo 'Validator not ready - sleeping 5s...'
          sleep 5
        done &&
        echo 'Validator is ready!' &&
        solana config set --url http://solana-validator:8899 &&
        echo 'Building all Solana programs...' &&
        mkdir -p target/deploy &&
        cargo build-sbf --manifest-path=programs/vault-sol/Cargo.toml &&
        cargo build-sbf --manifest-path=programs/locking-vault/Cargo.toml &&
        cargo build-sbf --manifest-path=programs/stablecoin-vault/Cargo.toml &&
        cargo build-sbf --manifest-path=programs/dual-product/Cargo.toml &&
        cp target/sbf-solana-solana/release/*.so target/deploy/ &&
        touch /workspace/.build-complete &&
        echo 'Build complete!'"
    depends_on:
      solana-validator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/workspace/.build-complete"]
      interval: 5s
      timeout: 5s
      retries: 10

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    environment:
      - ANCHOR_PROVIDER_URL=http://solana-validator:8899
      - ANCHOR_WALLET=/workspace/.anchor/wallet/wallet.json
    command: >
      bash -c "
        echo 'Waiting for program builds to complete...' &&
        until [ -f /workspace/.build-complete ]; do
          echo 'Waiting for program builds...'
          sleep 2
        done &&
        echo 'Running tests...' &&
        anchor test --skip-local-validator"
    depends_on:
      program-builder:
        condition: service_healthy

volumes:
  cargo-cache:
  target-cache: