services:
  solana-validator:
    image: solanalabs/solana:v1.14.17
    container_name: solana-validator
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    volumes:
      - ./target/deploy:/app/deploy
      - ./test-ledger:/test-ledger
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    command: >
      bash -c "
        apt-get update && apt-get install -y curl netcat &&
        echo 'Starting validator...' &&
        mkdir -p /test-ledger &&
        solana-test-validator 
          --ledger /test-ledger
          --bind-address 0.0.0.0
          --rpc-port 8899
          --rpc-bind-address 0.0.0.0
          --reset
          --slots-per-epoch 32
          --ticks-per-slot 8
          --account-paths /test-ledger/accounts
          --bpf-program-chunking-size 65536
          --deactivate-feature-stop-sibling-instruction-search
          --compute-unit-limit 1400000
          --log-messages-bytes-limit 65536
          --heap-size 256000000
          --enable-cpi-and-log-storage
          --skip-startup-ledger-verification
          --quiet"
    environment:
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
      - RUST_BACKTRACE=1
    networks:
      - solana-network
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8899", "-X", "POST", "-H", "Content-Type: application/json", "-d", '{"jsonrpc":"2.0","id":1,"method":"getHealth"}']
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s

  program-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: program-builder
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    command: >
      bash -c "
        apt-get update && apt-get install -y curl &&
        echo 'Waiting for Solana validator...' &&
        while ! curl -sf http://solana-validator:8899 -X POST -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getHealth\"}'; do
          echo 'Validator not ready - sleeping 5s...'
          sleep 5
        done &&
        echo 'Validator is ready!' &&
        solana config set --url http://solana-validator:8899 &&
        solana-keygen new --no-bip39-passphrase --force -o /root/.config/solana/id.json &&
        echo 'Setting up project dependencies...' &&
        cd /workspace &&
        echo 'Building individual programs...' &&
        mkdir -p target/deploy programs/target/deploy &&
        chmod -R 777 target programs/target &&
        cd programs/locking-vault &&
        cargo build-sbf --sbf-out-dir /workspace/target/deploy &&
        cp -f /workspace/target/deploy/*.so /workspace/programs/target/deploy/ &&
        cd ../stablecoin-vault &&
        cargo build-sbf --sbf-out-dir /workspace/target/deploy &&
        cp -f /workspace/target/deploy/*.so /workspace/programs/target/deploy/ &&
        cd ../dual-product &&
        cargo build-sbf --sbf-out-dir /workspace/target/deploy &&
        cp -f /workspace/target/deploy/*.so /workspace/programs/target/deploy/ &&
        cd ../vault-sol &&
        cargo build-sbf --sbf-out-dir /workspace/target/deploy &&
        cp -f /workspace/target/deploy/*.so /workspace/programs/target/deploy/ &&
        cd /workspace &&
        echo 'Build complete!' &&
        ls -la target/deploy/ &&
        ls -la programs/target/deploy/ || echo 'Programs deploy directory not found' &&
        chmod -R 777 target programs/target &&
        touch /workspace/.build-complete &&
        # Keep the container running
        tail -f /dev/null"
    networks:
      - solana-network
    depends_on:
      solana-validator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/workspace/.build-complete"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
    working_dir: /workspace
    environment:
      - ANCHOR_PROVIDER_URL=http://solana-validator:8899
      - ANCHOR_WALLET=/workspace/.anchor/wallet/wallet.json
      - RUST_BACKTRACE=full
    networks:
      - solana-network
    command: >
      bash -c "
        echo 'Waiting for program builds to complete...' &&
        until [ -f /workspace/.build-complete ]; do
          echo 'Waiting for program builds...'
          sleep 2
        done &&
        echo 'Setting script permissions...' &&
        chmod +x /workspace/run-full-tests.sh || true &&
        chmod +x /workspace/update-program-ids.sh || true &&
        chmod +x /workspace/setup-wallet-test.sh || true &&
        chmod +x /workspace/run_tests.sh || true &&
        echo 'Running the comprehensive test suite...' &&
        /workspace/run-full-tests.sh"
    depends_on:
      solana-validator:
        condition: service_healthy
      program-builder:
        condition: service_completed_successfully

volumes:
  cargo-cache:
  target-cache:

networks:
  solana-network:
    driver: bridge