[workspace]
members = [
    "vault-sol",
    "dual-product",
    "stablecoin-vault",
    "locking-vault",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1